// Package export renders the doc tree into shareable formats.
// Typescript is pure string building; stdlib only.
package export

import (
	"fmt"
	"strings"

	"github.com/erikwang2013/apidoc-go/model"
)

// Typescript returns deterministic TypeScript interface definitions for
// the project: one request-params interface per action plus one
// response interface per response, object params/responses expanded
// into nested interfaces. Store tree order; children as declared.
// An empty project yields the header comment only.
func Typescript(p *model.Project) string {
	g := &gen{used: map[string]bool{}}
	g.b.WriteString("// Generated by apidoc-go. Do not edit.\n")
	for _, app := range p.Apps {
		for _, v := range app.Versions {
			for _, c := range v.Controllers {
				for _, a := range c.Actions {
					g.action(app.Key, v.Name, c, a)
				}
			}
		}
	}
	return g.b.String()
}

// SanitizeIdent turns any string into a valid TypeScript identifier:
// every character outside [A-Za-z0-9_] becomes _, a leading digit gains
// a _ prefix, and an empty result becomes "_".
func SanitizeIdent(s string) string {
	var b strings.Builder
	for _, r := range s {
		if r >= 'a' && r <= 'z' || r >= 'A' && r <= 'Z' || r >= '0' && r <= '9' || r == '_' {
			b.WriteRune(r)
		} else {
			b.WriteByte('_')
		}
	}
	out := b.String()
	if out == "" {
		return "_"
	}
	if out[0] >= '0' && out[0] <= '9' {
		out = "_" + out
	}
	return out
}

type gen struct {
	b    strings.Builder
	used map[string]bool
}

// action writes the interfaces of one action: {Controller}_{Action}_Params
// plus one {Controller}_{Action}_{RespName} per response.
func (g *gen) action(app, version string, c *model.Controller, a *model.Action) {
	base := SanitizeIdent(c.Name)
	if base == "_" {
		base = "Default"
	}
	act := actionName(a.Method, a.URL)
	fmt.Fprintf(&g.b, "\n// %s/%s %s %s — %s\n", app, version, a.Method, a.URL, a.Title)
	g.interface_(g.unique(base+"_"+act+"_Params"), a.Params)
	for _, resp := range a.Responses {
		rn := capitalize(SanitizeIdent(resp.Name))
		if rn == "_" {
			rn = "Ok"
		}
		g.interface_(g.unique(base+"_"+act+"_"+rn), resp.Fields)
	}
}

// interface_ emits nested object interfaces (depth-first) before the
// parent interface.
func (g *gen) interface_(name string, fields []model.Param) {
	var body strings.Builder
	for _, f := range fields {
		nested := ""
		if len(f.Children) > 0 {
			nested = g.unique(name + "_" + SanitizeIdent(f.Name))
			g.interface_(nested, f.Children)
		}
		body.WriteString(g.fieldLine(f, nested))
	}
	fmt.Fprintf(&g.b, "export interface %s {\n%s}\n", name, body.String())
}

func (g *gen) fieldLine(f model.Param, nested string) string {
	t := strings.TrimPrefix(strings.TrimPrefix(f.Type, "{list}"), "*")
	typ := ""
	if strings.HasPrefix(t, "[]") {
		inner := strings.TrimPrefix(strings.TrimPrefix(t[2:], "{list}"), "*")
		if nested == "" {
			nested = primitive(inner)
		}
		typ = "Array<" + nested + ">"
	} else if nested != "" {
		typ = nested
	} else {
		typ = primitive(t)
	}
	opt := ""
	if !f.Required {
		opt = "?"
	}
	return fmt.Sprintf("  %s%s: %s\n", SanitizeIdent(f.Name), opt, typ)
}

// primitive maps a scalar doc type to its TypeScript equivalent;
// anything unknown or empty becomes any.
func primitive(t string) string {
	switch t {
	case "string":
		return "string"
	case "int", "int64", "float", "float64", "number", "double":
		return "number"
	case "bool", "boolean":
		return "boolean"
	case "file":
		return "any"
	case "object", "struct":
		return "Record<string, unknown>"
	case "array":
		return "Array<any>"
	case "map", "json", "any":
		return "any"
	}
	return "any"
}

// actionName derives a deterministic PascalCase action name from the
// method and URL path segments, e.g. GET /api/users/:id → GetApiUsersId.
func actionName(method, url string) string {
	var b strings.Builder
	for _, seg := range strings.FieldsFunc(url, func(r rune) bool {
		return r == '/' || r == ':' || r == '.' || r == '-' || r == ' '
	}) {
		s := SanitizeIdent(seg)
		if s == "_" {
			continue
		}
		b.WriteString(capitalize(s))
	}
	m := strings.ToLower(method)
	if m == "" {
		m = "get"
	}
	return capitalize(m) + b.String()
}

// unique returns name, or name_2/name_3/... on collision.
func (g *gen) unique(name string) string {
	if !g.used[name] {
		g.used[name] = true
		return name
	}
	for i := 2; ; i++ {
		cand := fmt.Sprintf("%s_%d", name, i)
		if !g.used[cand] {
			g.used[cand] = true
			return cand
		}
	}
}

func capitalize(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}
