package export

import (
	"strings"
	"testing"

	"github.com/erikwang2013/apidoc-go/model"
)

func testProject() *model.Project {
	return &model.Project{Name: "demo", Apps: []*model.App{{
		Key: "users", Title: "Users", Versions: []*model.Version{{
			Name: "v1", Controllers: []*model.Controller{{
				Name: "UserApi", Actions: []*model.Action{{
					Method: "GET", URL: "/api/users/:id", Title: "get",
					Params: []model.Param{
						{Name: "id", Type: "int", Required: true},
						{Name: "name", Type: "string"},
						{Name: "ok", Type: "bool"},
						{Name: "tags", Type: "[]string"},
						{Name: "addr", Type: "object", Children: []model.Param{
							{Name: "city", Type: "string", Required: true},
						}},
						{Name: "weird name", Type: "json"},
						{Name: "9lives", Type: "file"},
					},
					Responses: []model.Response{{
						Name: "ok", Type: "[]User", Fields: []model.Param{
							{Name: "id", Type: "int", Required: true},
							{Name: "email", Type: "string"},
						},
					}},
				}},
			}},
		}},
	}}}
}

func TestTypescript(t *testing.T) {
	ts := Typescript(testProject())
	for _, want := range []string{
		"// Generated by apidoc-go. Do not edit.",
		"export interface UserApi_GetApiUsersId_Params {",
		"  id: number",
		"  name?: string",
		"  ok?: boolean",
		"  tags?: Array<string>",
		"  addr?: UserApi_GetApiUsersId_Params_addr",
		"  weird_name?: any",
		"  _9lives?: any",
		"export interface UserApi_GetApiUsersId_Params_addr {",
		"  city: string",
		"export interface UserApi_GetApiUsersId_Ok {",
		"  id: number",
		"  email?: string",
	} {
		if !strings.Contains(ts, want) {
			t.Fatalf("typescript missing %q:\n%s", want, ts)
		}
	}
}

func TestTypescriptEmptyProject(t *testing.T) {
	if ts := Typescript(&model.Project{}); ts != "// Generated by apidoc-go. Do not edit.\n" {
		t.Fatalf("empty project: %q", ts)
	}
}

func TestTypescriptDedup(t *testing.T) {
	// two actions with identical controller+action names → _2 suffix
	p := testProject()
	c := p.Apps[0].Versions[0].Controllers[0]
	c.Actions = append(c.Actions, &model.Action{
		Method: "GET", URL: "/api/users/:id", Title: "dup",
		Params: []model.Param{{Name: "x", Type: "string", Required: true}},
	})
	ts := Typescript(p)
	if !strings.Contains(ts, "UserApi_GetApiUsersId_Params_2") {
		t.Fatalf("dedup missing _2 interface:\n%s", ts)
	}
}

func TestSanitizeIdent(t *testing.T) {
	cases := []struct{ in, want string }{
		{"users", "users"},
		{"9lives", "_9lives"},
		{"", "_"},
		{"a b-c.d", "a_b_c_d"},
		{"中文名", "___"},
	}
	for _, c := range cases {
		if got := SanitizeIdent(c.in); got != c.want {
			t.Fatalf("SanitizeIdent(%q)=%q, want %q", c.in, got, c.want)
		}
	}
}
