package server

import (
	"encoding/json"
	"net/http"
	"reflect"
	"strings"
	"testing"
	"time"

	"github.com/erikwang2013/apidoc-go/auth"
	"github.com/erikwang2013/apidoc-go/model"
	"github.com/erikwang2013/apidoc-go/store"
)

// exportStore builds a store covering every documented type mapping.
func exportStore() *store.Store {
	s := store.New("p")
	s.SetAppMeta("users", "Users")
	s.Register("GET", "/users", model.Doc{App: "users", Version: "v1", Title: "list",
		Params: []model.Param{
			{Name: "id", In: "query", Type: "string", Required: true},
			{Name: "age", In: "query", Type: "int"},
			{Name: "active", In: "query", Type: "bool", Required: true},
			{Name: "tags", In: "query", Type: "[]string"},
			{Name: "user", In: "query", Type: "object", Children: []model.Param{
				{Name: "id", Type: "int", Required: true},
				{Name: "name", Type: "string"},
			}},
			{Name: "mystery", In: "query", Type: "???"},
		},
		Responses: []model.Response{{Name: "ok", Type: "[]User", Fields: []model.Param{
			{Name: "id", Type: "int", Required: true},
			{Name: "name", Type: "string"},
		}}},
	})
	return s
}

func TestExportJSON(t *testing.T) {
	h := Handler(Opts{Prefix: "/apidoc", Store: exportStore()})
	rec := req(t, h, http.MethodGet, "/api/export", "")
	if rec.Code != http.StatusOK {
		t.Fatalf("export json status %d: %s", rec.Code, rec.Body.String())
	}
	var b struct {
		Code int           `json:"code"`
		Data model.Project `json:"data"`
	}
	if err := json.Unmarshal(rec.Body.Bytes(), &b); err != nil {
		t.Fatal(err)
	}
	if b.Code != 0 || len(b.Data.Apps) != 1 || len(b.Data.Apps[0].Versions) != 1 ||
		len(b.Data.Apps[0].Versions[0].Controllers) != 1 {
		t.Fatalf("project shape wrong: %+v", b.Data)
	}
	acts := b.Data.Apps[0].Versions[0].Controllers[0].Actions
	if len(acts) != 1 || len(acts[0].Params) != 6 || len(acts[0].Responses) != 1 {
		t.Fatalf("action content wrong: %+v", acts)
	}
	// format=json explicit behaves identically
	rec2 := req(t, h, http.MethodGet, "/api/export?format=json", "")
	if rec2.Code != http.StatusOK || !reflect.DeepEqual(rec2.Body.Bytes(), rec.Body.Bytes()) {
		t.Fatalf("explicit format=json differs from default")
	}
}

func TestExportTypescript(t *testing.T) {
	s := exportStore()
	h := Handler(Opts{Prefix: "/apidoc", Store: s})
	rec := req(t, h, http.MethodGet, "/api/export?format=typescript", "")
	if rec.Code != http.StatusOK {
		t.Fatalf("export ts status %d: %s", rec.Code, rec.Body.String())
	}
	if ct := rec.Header().Get("Content-Type"); !strings.HasPrefix(ct, "text/plain") {
		t.Fatalf("ts content-type %q", ct)
	}
	var b struct {
		Code int    `json:"code"`
		Data string `json:"data"`
	}
	if err := json.Unmarshal(rec.Body.Bytes(), &b); err != nil || b.Code != 0 {
		t.Fatalf("ts envelope wrong: %s", rec.Body.String())
	}
	ts := b.Data
	ctrl := store.ActionID("users", "v1", "GET", "/users")
	a, _ := s.Action(ctrl)
	base := a.Controller + "_GetUsers"
	for _, want := range []string{
		"// Generated by apidoc-go. Do not edit.",
		"export interface " + base + "_Params {",
		"  id: string",
		"  age?: number", // optional int
		"  active: boolean",
		"  tags?: Array<string>",
		"  user?: " + base + "_Params_user", // nested object ref
		"  mystery?: any",                   // unknown type
		"export interface " + base + "_Params_user {",
		"  id: number",
		"  name?: string",
		"export interface " + base + "_Ok {",
		"  name?: string",
	} {
		if !strings.Contains(ts, want) {
			t.Fatalf("ts missing %q:\n%s", want, ts)
		}
	}
}

func TestExportDeterministic(t *testing.T) {
	h := Handler(Opts{Prefix: "/apidoc", Store: exportStore()})
	first := req(t, h, http.MethodGet, "/api/export?format=json", "")
	second := req(t, h, http.MethodGet, "/api/export?format=json", "")
	if !reflect.DeepEqual(first.Body.Bytes(), second.Body.Bytes()) {
		t.Fatal("export json not deterministic")
	}
	var a, b any
	if err := json.Unmarshal(first.Body.Bytes(), &a); err != nil {
		t.Fatal(err)
	}
	if err := json.Unmarshal(second.Body.Bytes(), &b); err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(a, b) {
		t.Fatal("export json deep-equal failed")
	}
}

func TestExportUnknownFormat(t *testing.T) {
	h := Handler(Opts{Prefix: "/apidoc", Store: newTestStore()})
	rec := req(t, h, http.MethodGet, "/api/export?format=bogus", "")
	if rec.Code != http.StatusBadRequest {
		t.Fatalf("bogus format: want 400 got %d", rec.Code)
	}
}

func TestExportAuthGating(t *testing.T) {
	h := Handler(Opts{Prefix: "/apidoc", Store: newTestStore(),
		Auth: auth.Config{Enable: true, Password: "pw", Secret: "sec", Expire: time.Hour}})
	if rec := req(t, h, http.MethodGet, "/api/export?format=json", ""); rec.Code != http.StatusUnauthorized {
		t.Fatalf("export without cookie: want 401 got %d", rec.Code)
	}
	if rec := req(t, h, http.MethodGet, "/api/export?format=typescript", ""); rec.Code != http.StatusUnauthorized {
		t.Fatalf("export ts without cookie: want 401 got %d", rec.Code)
	}
	login := req(t, h, http.MethodPost, "/api/login", `{"password":"pw"}`)
	if login.Code != http.StatusOK {
		t.Fatalf("login: %d %s", login.Code, login.Body.String())
	}
	cookies := login.Result().Cookies()
	if rec := req(t, h, http.MethodGet, "/api/export?format=json", "", cookies[0]); rec.Code != http.StatusOK {
		t.Fatalf("export with cookie: want 200 got %d", rec.Code)
	}
}
